@Lil.TimeTracking_HostAddress = https://localhost:7208

GET {{Lil.TimeTracking_HostAddress}}/weatherforecast/
Accept: application/json

###

GET {{Lil.TimeTracking_HostAddress}}/api/Employee
Accept: application/json

###

GET {{Lil.TimeTracking_HostAddress}}/api/Employee/1
Accept: application/json

###
POST {{Lil.TimeTracking_HostAddress}}/api/Employee
Content-Type: application/json

{
  "name":"Iman 2",
  "startDate" :"2024-05-05"
}

###
PUT {{Lil.TimeTracking_HostAddress}}/api/Employee/1
Content-Type: application/json

{
  "Id":1,
  "Name":"Iman its updated",
  "StartDate" :"2024-02-05"
}
###
PATCH {{Lil.TimeTracking_HostAddress}}/api/Employee/1
Content-Type: application/json

[
  {
  "op":"add",
  "path":"/name",
  "value":"Employee 2 patched",
  }
]
###
DELETE {{Lil.TimeTracking_HostAddress}}/api/Employee/1


###